# Generated by Django 3.0.7 on 2020-07-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tollywood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='prodcer',
            new_name='producer',
        ),
    ]
